cf_labs_git: https://github.com/opsforge/cf-labs.git
cf_labs_git_branch: master

s3_endpoint: http://minio:9000
s3_bucket: terraform
s3_regexp: (.*).tfstate
# Don't change following unless adjusted keys in minio deployment too
s3_access_key_id: AKIAIOSFODNN7EXAMPLE
s3_secret_access_key: wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY

aws_tf_access_key: OMIT
aws_tf_secret_key: OMIT
