cf_labs_git: https://github.com/opsforge/cf-labs.git
cf_labs_git_branch: master

region: eu-west-1
s3_bucket: terraform-16c8d10f-f792-4297-87e4-39c53d3d7320
s3_regexp: (.*).tfstate

# Keep commented out below if using -v arguments to pass to fly (avoiding accidental git commits)
aws_tf_access_key: MYMAGICKEY
aws_tf_secret_key: MYMAGICSECRET

ec2_instance_key: 'MYPUBLIC_KEY'
