resources:

- name: cf-labs
  check_every: 30s
  type: git
  source:
    uri: {{cf_labs_git}}
    branch: {{cf_labs_git_branch}}

    # - name: terraform-state
    #   # Upped the freq to help with troubleshooting, feel free to drop
    #   check_every: 20s
    #   type: s3
    #   source:
    #     access_key_id: {{aws_tf_access_key}}
    #     secret_access_key: {{aws_tf_secret_key}}
    #     region: {{region}}
    #     bucket: {{s3_bucket}}
    #     # This doesn't work with a fixed filename for no good reason
    #     regexp: '(.*).tfstate'
    
- name: terraform-state
  check_every: 20s
  type: s3
  source:
    disable_ssl: false
    access_key_id: {{aws_tf_access_key}}
    secret_access_key: {{aws_tf_secret_key}}
    endpoint: {{s3_endpoint}}
    bucket: {{s3_bucket}}
    region_name: {{aws_region}}
    versioned_file: terraform.tfstate



jobs:

- name: bootstrap-terraform-state
  serial_groups: [terraform]
  plan:
  - get: cf-labs
    trigger: true
  - task: create-terraform-state
    params:
      S3_BUCKET_TERRAFORM: {{s3_bucket}}
      REGION: {{region}}
      AWS_ACCESS_KEY_ID: {{aws_tf_access_key}}
      AWS_SECRET_ACCESS_KEY: {{aws_tf_secret_key}}
    # This goes off and creates the tfstate (empty) and its bucket too if missing
    file: cf-labs/tasks/create-initial-terraform-state/task.yml

- name: pave-bosh-lite
  serial_groups: [terraform]
  plan:
  - aggregate:
    - get: cf-labs
    - get: terraform-state
      # Gets triggered by the terraform-state get because that only passes if bootstrap passed too
      # trigger: true
  - task: plan-terraform
    config: &tf_plan_block
      platform: linux
      inputs: &tf_inputs
        - name: cf-labs
        - name: terraform-state
      outputs:
        - name: plans
      image_resource: &tf_image
        type: docker-image
        source:
          repository: pcfnorm/rootfs
      run:
        path: sh
        args:
          - -exc
          - |
            cat terraform-state/terraform.tfstate &&
            terraform init cf-labs/pipelines/awslab/terraform &&
            terraform plan -state terraform-state/terraform.tfstate \
            -var 'ec2_key_pair_pub={{ec2_instance_key}}' \
            -var 'aws_access_key={{aws_tf_access_key}}' \
            -var 'aws_secret_key={{aws_tf_secret_key}}' \
            -out plans/terraform.tfplan \
            cf-labs/pipelines/awslab/terraform
  - task: apply-terraform
    config: &tf_apply_block
      platform: linux
      inputs:
        - name: cf-labs
        - name: plans
      outputs:
        - name: terraform-state-out
      image_resource: *tf_image
      run:
        path: sh
        args:
          - -exc
          - |
            terraform init cf-labs/pipelines/awslab/terraform &&
            terraform apply -auto-approve \
            -state-out terraform-state-out/terraform.tfstate \
            plans/terraform.tfplan
    ensure: &tf_save_state
      put: terraform-state
      params:
        file: terraform-state-out/terraform.tfstate
        acl: private



- name: wipe-terraform
  serial_groups: [terraform]
  plan:
  - aggregate:
    - get: cf-labs
    - get: terraform-state
  # - task: plan-terraform
  #   config: *tf_plan_block
  - task: wipe-terraform
    config: &tf_wipe_block
      platform: linux
      inputs: *tf_inputs
      outputs:
        - name: terraform-state-out
      image_resource: *tf_image
      run:
        path: sh
        args:
          - -exc
          - |
            cat terraform-state/terraform.tfstate &&
            terraform init cf-labs/pipelines/awslab/terraform &&
            terraform destroy -force -state terraform-state/terraform.tfstate \
            -var 'ec2_key_pair_pub={{ec2_instance_key}}' \
            -var 'aws_access_key={{aws_tf_access_key}}' \
            -var 'aws_secret_key={{aws_tf_secret_key}}' \
            -state-out terraform-state-out/terraform.tfstate \
            cf-labs/pipelines/awslab/terraform
  ensure: *tf_save_state
