resources:

- name: cf-labs
  type: git
  source:
    uri: {{cf_labs_git}}
    branch: {{cf_labs_git_branch}}

- name: terraform-state
  type: s3
  source:
    disable_ssl: false
    access_key_id: {{s3_access_key_id}}
    secret_access_key: {{s3_secret_access_key}}
    endpoint: {{s3_endpoint}}
    bucket: {{s3_bucket}}
    versioned_file: terraform.tfstate




jobs:

- name: bootstrap-terraform-state
  serial_groups: [terraform]
  plan:
  - get: cf-labs
  - task: create-terraform-state
    params:
      S3_BUCKET_TERRAFORM: {{s3_bucket}}
      S3_ENDPOINT: {{s3_endpoint}}
      AWS_ACCESS_KEY_ID: {{s3_access_key_id}}
      AWS_SECRET_ACCESS_KEY: {{s3_secret_access_key}}
    file: cf-labs/tasks/create-initial-terraform-state/task.yml

- name: check-terraform-state
  serial_groups: [terraform]
  plan:
  - aggregate:
    - get: cf-labs
    - get: terraform-state
    trigger: true
    passed: [bootstrap-terraform-state]
  - task: create-terraform-state
    config:
      platform: linux
      inputs:
        - name: cf-labs
        - name: terraform-state
      image_resource:
        type: docker-image
        source:
          repository: alpine/git
      run:
        path: sh
        args:
        - -c
        - |
          ls -la
          ls -la ./cf-labs
          ls -la ./terraform-state


















# jobs:
# - name: list-folders
#   plan:
#   - get: pcf-labs
#   - task: why
#     config:
#       platform: linux
#       inputs:
#       - name: pcf-labs
#       outputs:
#       - name: terraform
#       image_resource:
#         type: docker-image
#         source:
#           repository: alpine/git
#           # tag: 18.04
#       run:
#         path: sh
#         args:
#         - -c
#         - |
#           ls -la ./
#           echo "{mystate}" > ./terraform/terraform.tfstate
#   - task: hello
#     config:
#       platform: linux
#       inputs:
#       - name: terraform
#       image_resource:
#         type: docker-image
#         source:
#           repository: alpine/git
#           # tag: 18.04
#       run:
#         path: sh
#         args:
#         - -c
#         - |
#           ls -la ./
#   - put: terraform-state
#     params:
#       file: terraform/terraform.tfstate
#       acl: private
