resources:

- name: pcf-labs
  type: git
  source:
    uri: https://github.com/opsforge/cf-labs.git
    branch: master

jobs:
- name: list-folders
  plan:
  - get: pcf-labs
  - task: why
    config:
      platform: linux
      image_resource:
        type: docker-image
        source:
          repository: alpine/git
          # tag: 18.04
      run:
        path: sh
        args:
        - -c
        - |
          ls -la ./
