---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: pcfnorm/rootfs

inputs:
- name: cf-labs

params:
  S3_BUCKET_TERRAFORM:
  REGION:
  AWS_ACCESS_KEY_ID:
  AWS_SECRET_ACCESS_KEY:

run:
  path: cf-labs/tasks/create-initial-terraform-state/task.sh
